//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.FactoryFinishedProduct.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryFinishedProductPrice
    {
        public int FactoryFinishedProductPriceID { get; set; }
        public Nullable<int> FactoryFinishedProductID { get; set; }
        public Nullable<int> FactoryTeamID { get; set; }
        public Nullable<int> FactoryStepID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> HalfRoundPrice { get; set; }
        public Nullable<decimal> DoubleRoundPrice { get; set; }
    
        public virtual FactoryFinishedProduct FactoryFinishedProduct { get; set; }
    }
}
