//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.WarehouseTransportMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseTransportProductDetail
    {
        public int WarehouseTransportProductDetailID { get; set; }
        public Nullable<int> FromWarehouseAreaID { get; set; }
        public Nullable<int> ToWarehouseAreaID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductStatusID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual WarehouseTransport WarehouseTransport { get; set; }
    }
}
