//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ProductMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMng_Package_Constant_View
    {
        public int ConstantEntryID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public string PackageNM { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
