//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SaleOrderMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_PaymentStatus_View
    {
        public int ConstantEntryID { get; set; }
        public Nullable<int> PaymentStatusID { get; set; }
        public string PaymentStatusNM { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
