//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SaleOrderMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderDetailSparepart_Return
    {
        public SaleOrderDetailSparepart_Return()
        {
            this.SaleOrderSparepartReturn = new HashSet<SaleOrderSparepartReturn>();
            this.WarehouseImportSparepartDetail = new HashSet<WarehouseImportSparepartDetail>();
        }
    
        public int SaleOrderDetailSparepartID { get; set; }
        public Nullable<int> OrderQnt { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> ProductStatusID { get; set; }
        public Nullable<int> V4ID { get; set; }
    
        public virtual OfferLineSparepart_Return OfferLineSparepart { get; set; }
        public virtual SaleOrder_Return SaleOrder { get; set; }
        public virtual ICollection<SaleOrderSparepartReturn> SaleOrderSparepartReturn { get; set; }
        public virtual ICollection<WarehouseImportSparepartDetail> WarehouseImportSparepartDetail { get; set; }
    }
}
