//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SaleOrderMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderDetail_ReportView
    {
        public SaleOrderDetail_ReportView()
        {
            this.SaleOrderDetailExtend_ReportView = new HashSet<SaleOrderDetailExtend_ReportView>();
        }
    
        public int SaleOrderDetailID { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
        public string ArticleCode { get; set; }
        public string Description { get; set; }
        public string ClientArticleCode { get; set; }
        public string ClientArticleName { get; set; }
        public string ClientOrderNumber { get; set; }
        public string ClientEANCode { get; set; }
        public string Reference { get; set; }
        public Nullable<int> OrderQnt { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public Nullable<int> RowIndex { get; set; }
    
        public virtual SaleOrder_ReportView SaleOrder_ReportView { get; set; }
        public virtual ICollection<SaleOrderDetailExtend_ReportView> SaleOrderDetailExtend_ReportView { get; set; }
    }
}
