//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SaleOrderMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderMng_FactoryOrderDetail_OverView
    {
        public SaleOrderMng_FactoryOrderDetail_OverView()
        {
            this.SaleOrderMng_FactoryOrderDetailQCReport_OverView = new HashSet<SaleOrderMng_FactoryOrderDetailQCReport_OverView>();
        }
    
        public int FactoryOrderDetailID { get; set; }
        public Nullable<int> SaleOrderDetailID { get; set; }
        public string LDS { get; set; }
        public string ETD { get; set; }
        public int OrderQnt { get; set; }
        public int ShippedQnt { get; set; }
        public Nullable<int> FactoryID { get; set; }
        public string FactoryUD { get; set; }
        public string Season { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> TotalQnt { get; set; }
        public Nullable<int> FactoryOrderID { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
    
        public virtual ICollection<SaleOrderMng_FactoryOrderDetailQCReport_OverView> SaleOrderMng_FactoryOrderDetailQCReport_OverView { get; set; }
    }
}
