//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.BackSaleOrderMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackOrderDetail
    {
        public int BackOrderDetailID { get; set; }
        public Nullable<int> OriginQnt { get; set; }
        public Nullable<int> BackQnt { get; set; }
    
        public virtual SaleOrderDetail BackSaleOrderDetail { get; set; }
        public virtual SaleOrderDetailSparepart BackSaleOrderDetailSparepart { get; set; }
        public virtual SaleOrderDetail OriginSaleOrderDetail { get; set; }
        public virtual SaleOrderDetailSparepart OriginSaleOrderDetailSparepart { get; set; }
        public virtual BackOrder BackOrder { get; set; }
    }
}
