//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.BackSaleOrderMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderDetail
    {
        public SaleOrderDetail()
        {
            this.BackSaleOrderDetail = new HashSet<BackOrderDetail>();
            this.OriginSaleOrderDetail = new HashSet<BackOrderDetail>();
        }
    
        public int SaleOrderDetailID { get; set; }
        public Nullable<int> OrderQnt { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string ClientArticleCode { get; set; }
        public string ClientArticleName { get; set; }
        public string ClientOrderNumber { get; set; }
        public string ClientEANCode { get; set; }
        public string Reference { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ProductStatusID { get; set; }
        public Nullable<int> V4ID { get; set; }
    
        public virtual OfferLine OfferLine { get; set; }
        public virtual ICollection<BackOrderDetail> BackSaleOrderDetail { get; set; }
        public virtual ICollection<BackOrderDetail> OriginSaleOrderDetail { get; set; }
        public virtual SaleOrder SaleOrder { get; set; }
    }
}
