//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.PlanningProductionMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanningProductionMng_GrantChart_PlanningProductionTeam_View
    {
        public int PlanningProductionTeamID { get; set; }
        public Nullable<int> PlanningProductionID { get; set; }
        public Nullable<int> BOMID { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public Nullable<int> WorkCenterID { get; set; }
        public Nullable<int> ProductionItemID { get; set; }
        public Nullable<int> ProductionTeamID { get; set; }
        public Nullable<decimal> PlanQnt { get; set; }
        public string ProductionTeamNM { get; set; }
        public string ProductionItemUD { get; set; }
        public Nullable<long> RowIndex { get; set; }
    }
}
