//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.FactoryTeam.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FactoryTeamEntities : DbContext
    {
        public FactoryTeamEntities()
            : base("name=FactoryTeamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FactoryTeam> FactoryTeam { get; set; }
        public virtual DbSet<FactoryTeamStep> FactoryTeamStep { get; set; }
        public virtual DbSet<FactoryMaterialGroupTeam> FactoryMaterialGroupTeam { get; set; }
    
        public virtual ObjectResult<FactoryTeam> FactoryTeamMng_function_SearchFactoryTeam(string sortedBy, string sortedDirection, string factoryTeamUD, string factoryTeamNM, Nullable<int> factoryStepID)
        {
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            var factoryTeamUDParameter = factoryTeamUD != null ?
                new ObjectParameter("FactoryTeamUD", factoryTeamUD) :
                new ObjectParameter("FactoryTeamUD", typeof(string));
    
            var factoryTeamNMParameter = factoryTeamNM != null ?
                new ObjectParameter("FactoryTeamNM", factoryTeamNM) :
                new ObjectParameter("FactoryTeamNM", typeof(string));
    
            var factoryStepIDParameter = factoryStepID.HasValue ?
                new ObjectParameter("FactoryStepID", factoryStepID) :
                new ObjectParameter("FactoryStepID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryTeam>("FactoryTeamMng_function_SearchFactoryTeam", sortedByParameter, sortedDirectionParameter, factoryTeamUDParameter, factoryTeamNMParameter, factoryStepIDParameter);
        }
    
        public virtual ObjectResult<FactoryTeam> FactoryTeamMng_function_SearchFactoryTeam(string sortedBy, string sortedDirection, string factoryTeamUD, string factoryTeamNM, Nullable<int> factoryStepID, MergeOption mergeOption)
        {
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            var factoryTeamUDParameter = factoryTeamUD != null ?
                new ObjectParameter("FactoryTeamUD", factoryTeamUD) :
                new ObjectParameter("FactoryTeamUD", typeof(string));
    
            var factoryTeamNMParameter = factoryTeamNM != null ?
                new ObjectParameter("FactoryTeamNM", factoryTeamNM) :
                new ObjectParameter("FactoryTeamNM", typeof(string));
    
            var factoryStepIDParameter = factoryStepID.HasValue ?
                new ObjectParameter("FactoryStepID", factoryStepID) :
                new ObjectParameter("FactoryStepID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryTeam>("FactoryTeamMng_function_SearchFactoryTeam", mergeOption, sortedByParameter, sortedDirectionParameter, factoryTeamUDParameter, factoryTeamNMParameter, factoryStepIDParameter);
        }
    }
}
