//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FactoryOrderMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryOrderMng_FactoryOrderDetail_OverView
    {
        public FactoryOrderMng_FactoryOrderDetail_OverView()
        {
            this.FactoryOrderMng_FactoryOrderColliDetail_OverView = new HashSet<FactoryOrderMng_FactoryOrderColliDetail_OverView>();
        }
    
        public int FactoryOrderDetailID { get; set; }
        public Nullable<int> FactoryOrderID { get; set; }
        public Nullable<int> SaleOrderDetailID { get; set; }
        public Nullable<int> OrderQnt { get; set; }
        public string Remark { get; set; }
        public Nullable<int> V4ID { get; set; }
        public string ArticleCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> SaleOrderQnt { get; set; }
        public Nullable<int> RemainQnt { get; set; }
        public Nullable<int> TotalQnt { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> BOMStandardID { get; set; }
        public Nullable<int> BOMID { get; set; }
    
        public virtual ICollection<FactoryOrderMng_FactoryOrderColliDetail_OverView> FactoryOrderMng_FactoryOrderColliDetail_OverView { get; set; }
        public virtual FactoryOrderMng_FactoryOrder_OverView FactoryOrderMng_FactoryOrder_OverView { get; set; }
    }
}
