//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FactoryOrderMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryOrderMng_FactoryOrderDetail_View
    {
        public FactoryOrderMng_FactoryOrderDetail_View()
        {
            this.FactoryOrderMng_FactoryOrderColliDetail_View = new HashSet<FactoryOrderMng_FactoryOrderColliDetail_View>();
        }
    
        public int FactoryOrderDetailID { get; set; }
        public Nullable<int> FactoryOrderID { get; set; }
        public Nullable<int> SaleOrderDetailID { get; set; }
        public Nullable<int> OrderQnt { get; set; }
        public string Remark { get; set; }
        public string ArticleCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> SaleOrderQnt { get; set; }
        public Nullable<int> V4ID { get; set; }
        public Nullable<int> RemainQnt { get; set; }
        public Nullable<int> TotalQnt { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
        public Nullable<int> LoadedQnt { get; set; }
        public Nullable<int> QAQCID { get; set; }
    
        public virtual FactoryOrderMng_FactoryOrder_View FactoryOrderMng_FactoryOrder_View { get; set; }
        public virtual ICollection<FactoryOrderMng_FactoryOrderColliDetail_View> FactoryOrderMng_FactoryOrderColliDetail_View { get; set; }
    }
}
