//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.MISaleByClientRpt.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISaleByClientRpt_EurofarCommercialInvoice_View
    {
        public int ClientID { get; set; }
        public string ClientUD { get; set; }
        public string ClientNM { get; set; }
        public string SaleUD { get; set; }
        public Nullable<decimal> CiContThisYear { get; set; }
        public Nullable<decimal> CiContLastYear { get; set; }
        public Nullable<decimal> CiContLastLastYear { get; set; }
        public Nullable<decimal> CiAmountInUSDThisYear { get; set; }
        public Nullable<decimal> CiAmountInUSDLastYear { get; set; }
        public Nullable<decimal> CiAmountInUSDLastLastYear { get; set; }
    }
}
