//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.QCReportMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCReportMng_QCReportFactoryOrderDetail_View
    {
        public int QCReportFactoryOrderDetailID { get; set; }
        public Nullable<int> QCReportID { get; set; }
        public Nullable<int> FactoryOrderDetailID { get; set; }
        public Nullable<int> FactoryOrderID { get; set; }
        public Nullable<int> FactoryID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string FactoryOrderUD { get; set; }
        public string ProformaInvoiceNo { get; set; }
        public Nullable<int> OrderQnt { get; set; }
        public string AdditionalRemark { get; set; }
        public string ProductionStatus { get; set; }
        public string LDS { get; set; }
        public string ArticleCode { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    
        public virtual QCReportMng_QCReport_View2 QCReportMng_QCReport_View2 { get; set; }
    }
}
