//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.QCReportMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCReportMng_QCReport_View2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QCReportMng_QCReport_View2()
        {
            this.QCReportMng_QCReportDefect_View2 = new HashSet<QCReportMng_QCReportDefect_View2>();
            this.QCReportMng_QCReportDetail_View2 = new HashSet<QCReportMng_QCReportDetail_View2>();
            this.QCReportMng_QCReportImage_View2 = new HashSet<QCReportMng_QCReportImage_View2>();
            this.QCReportMng_QCReportSummary_View = new HashSet<QCReportMng_QCReportSummary_View>();
            this.QCReportMng_QCReportTestEnvironment_View = new HashSet<QCReportMng_QCReportTestEnvironment_View>();
            this.QCReportMng_QCReportFactoryOrderDetail_View = new HashSet<QCReportMng_QCReportFactoryOrderDetail_View>();
        }
    
        public int QCReportID { get; set; }
        public string QCReportUD { get; set; }
        public Nullable<System.DateTime> InspectedDate { get; set; }
        public Nullable<int> FactoryID { get; set; }
        public Nullable<int> InspectionStageID { get; set; }
        public string SampleSize { get; set; }
        public string Location { get; set; }
        public string AssemplySampleSize { get; set; }
        public string QCName { get; set; }
        public Nullable<int> InspectedPackedQuantity { get; set; }
        public Nullable<int> InspectedNotPackedQuantity { get; set; }
        public Nullable<int> InspectedPackedCartonQuantity { get; set; }
        public Nullable<int> InspectedNotPackedCartonQuantity { get; set; }
        public Nullable<int> SaleOrderDetailID { get; set; }
        public Nullable<decimal> AQLCritical { get; set; }
        public Nullable<decimal> AQLMajor { get; set; }
        public Nullable<decimal> AQLMinor { get; set; }
        public Nullable<int> InspectionResultID { get; set; }
        public string InspectionResultNM { get; set; }
        public string ProformaInvoiceNo { get; set; }
        public string ArticleCode { get; set; }
        public string Description { get; set; }
        public string FactoryUD { get; set; }
        public string FactoryName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientUD { get; set; }
        public string ClientNM { get; set; }
        public string InspectionStageNM { get; set; }
        public string ProductImage { get; set; }
        public string ThumbnailLocation { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<int> PackagingMethodID { get; set; }
        public string PackagingMethodNM { get; set; }
        public Nullable<bool> IsConformed { get; set; }
        public string BeginInspection { get; set; }
        public string EndInspection { get; set; }
        public string FileLocation { get; set; }
        public string FriendlyName { get; set; }
        public Nullable<decimal> MaximumCritical { get; set; }
        public Nullable<decimal> MaximumMajor { get; set; }
        public Nullable<decimal> MaximumMinor { get; set; }
        public string ReportFile { get; set; }
        public string ReportFileLocation { get; set; }
        public string ReportFriendlyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QCReportMng_QCReportDefect_View2> QCReportMng_QCReportDefect_View2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QCReportMng_QCReportDetail_View2> QCReportMng_QCReportDetail_View2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QCReportMng_QCReportImage_View2> QCReportMng_QCReportImage_View2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QCReportMng_QCReportSummary_View> QCReportMng_QCReportSummary_View { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QCReportMng_QCReportTestEnvironment_View> QCReportMng_QCReportTestEnvironment_View { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QCReportMng_QCReportFactoryOrderDetail_View> QCReportMng_QCReportFactoryOrderDetail_View { get; set; }
    }
}
