//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.ProductionCosting.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionCostingMng_WorkOrder_View
    {
        public int WorkOrderID { get; set; }
        public string WorkOrderUD { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<decimal> WastagePercent { get; set; }
        public string ClientUD { get; set; }
        public string ModelUD { get; set; }
        public string ModelNM { get; set; }
        public string OPSequenceNM { get; set; }
        public string ProformaInvoiceNo { get; set; }
        public string ProductArticleCode { get; set; }
        public string ProductDescription { get; set; }
        public string WorkOrderTypeNM { get; set; }
        public string WorkOrderStatusNM { get; set; }
        public string SampleOrderInfo { get; set; }
        public string PreOrderDescription { get; set; }
    }
}
