//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.FactoryInvoiceOtherMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryInvoice
    {
        public FactoryInvoice()
        {
            this.FactoryInvoiceExtra = new HashSet<FactoryInvoiceExtra>();
        }
    
        public int FactoryInvoiceID { get; set; }
        public string Season { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<decimal> SubTotalAmount { get; set; }
        public Nullable<decimal> DeductedAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string ScanFile { get; set; }
        public string Remark { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public byte[] ConcurrencyFlag { get; set; }
    
        public virtual ICollection<FactoryInvoiceExtra> FactoryInvoiceExtra { get; set; }
    }
}
