//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.WarehouseReservationMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseReservation
    {
        public WarehouseReservation()
        {
            this.WarehouseReservationProductDetail = new HashSet<WarehouseReservationProductDetail>();
        }
    
        public int WarehouseReservationID { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<System.DateTime> ReservedDate { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ProcessingStatusID { get; set; }
        public Nullable<int> StatusUpdatedBy { get; set; }
        public Nullable<System.DateTime> StatusUpdatedDate { get; set; }
        public byte[] ConcurrencyFlag { get; set; }
    
        public virtual ICollection<WarehouseReservationProductDetail> WarehouseReservationProductDetail { get; set; }
    }
}
