//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.TaskMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskMng_TaskFile_View
    {
        public int TaskFileID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string FileUD { get; set; }
        public string Description { get; set; }
        public string FileLocation { get; set; }
        public string FriendlyName { get; set; }
    
        public virtual TaskMng_Task_View TaskMng_Task_View { get; set; }
    }
}
