//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.QualityInspectionRpt.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityInspectionRpt_QualityInspectionDefaultSetting_View
    {
        public int QualityInspectionDefaultSettingID { get; set; }
        public string QualityInspectionDefaultSection { get; set; }
        public string Description { get; set; }
    }
}
