//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.SeatCushionMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatCushionMng_SeatCushion_View
    {
        public SeatCushionMng_SeatCushion_View()
        {
            this.SeatCushionMng_SeatCushionProductGroup_View = new HashSet<SeatCushionMng_SeatCushionProductGroup_View>();
        }
    
        public int SeatCushionID { get; set; }
        public string SeatCushionUD { get; set; }
        public string SeatCushionNM { get; set; }
        public string Season { get; set; }
        public string ImageFile { get; set; }
        public Nullable<bool> IsStandard { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] ConcurrencyFlag { get; set; }
        public string UpdatorName { get; set; }
        public string ImageFile_DisplayUrl { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatorName { get; set; }
        public string CreatorName2 { get; set; }
        public string UpdatorName2 { get; set; }
    
        public virtual ICollection<SeatCushionMng_SeatCushionProductGroup_View> SeatCushionMng_SeatCushionProductGroup_View { get; set; }
    }
}
