//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.WEXStockOverviewRpt.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPurchasingPrice
    {
        public int ProductPurchasingPriceID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> PurchasingPrice { get; set; }
        public Nullable<int> Obsolete { get; set; }
        public Nullable<decimal> ValueObsolescence { get; set; }
    }
}
