//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.AccountPayableRpt.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPayableMng_PurchaseInvoice_View
    {
        public int PurchaseInvoiceID { get; set; }
        public string PurchaseInvoiceUD { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> FactoryRawMaterialID { get; set; }
        public Nullable<int> PurchaseInvoiceStatusID { get; set; }
        public string Currency { get; set; }
        public string FactoryRawMaterialOfficialNM { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PurchaseInvoiceDate { get; set; }
        public string DueDate { get; set; }
        public Nullable<int> DueDay { get; set; }
        public Nullable<int> KeyRawMaterialID { get; set; }
        public string keyRawMaterialNM { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> TotalRemain { get; set; }
    }
}
