//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.LoadingPlanMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryOrderSparepartDetail
    {
        public FactoryOrderSparepartDetail()
        {
            this.LoadingPlanSparepartDetail = new HashSet<LoadingPlanSparepartDetail>();
        }
    
        public int FactoryOrderSparepartDetailID { get; set; }
        public Nullable<int> FactoryOrderID { get; set; }
        public Nullable<int> SaleOrderDetailSparepartID { get; set; }
        public Nullable<int> OrderQnt { get; set; }
        public string Remark { get; set; }
        public Nullable<int> V4ID { get; set; }
        public Nullable<int> V4SaleOrderDetailID { get; set; }
    
        public virtual ICollection<LoadingPlanSparepartDetail> LoadingPlanSparepartDetail { get; set; }
    }
}
