//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.LoadingPlanMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingPlanMng_LoadingPlanSearchResult_View
    {
        public int LoadingPlanID { get; set; }
        public string IsSent { get; set; }
        public Nullable<bool> IsLoaded { get; set; }
        public Nullable<bool> IsShipped { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string LoadingPlanUD { get; set; }
        public string ContainerRefNo { get; set; }
        public string ClientUD { get; set; }
        public string FactoryUD { get; set; }
        public string ControllerName { get; set; }
        public string BookingUD { get; set; }
        public string BLNo { get; set; }
        public string ContainerNo { get; set; }
        public string ContainerTypeNM { get; set; }
        public Nullable<System.DateTime> LoadingDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public string SenderName { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string ConfirmerName { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public string UpdatorName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string PINo { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> ContainerTypeID { get; set; }
        public Nullable<bool> IsCreatedInvoice { get; set; }
        public string SealNo { get; set; }
        public Nullable<int> FactoryID { get; set; }
        public Nullable<int> ConfirmerID { get; set; }
        public Nullable<int> UpdatorID { get; set; }
        public Nullable<decimal> TotalOrderQnt40HC { get; set; }
        public Nullable<int> ControllerID { get; set; }
        public Nullable<bool> IsUploadingImageFinish { get; set; }
        public Nullable<int> LoadQnt { get; set; }
        public Nullable<int> CTNS { get; set; }
        public Nullable<decimal> NW { get; set; }
        public Nullable<decimal> GW { get; set; }
        public Nullable<decimal> CBMS { get; set; }
    }
}
