//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.MIEurofarPriceOverviewRpt.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIEurofarPriceOverviewRpt_Supplier_HTML_View
    {
        public long PrimaryID { get; set; }
        public string Season { get; set; }
        public string FactoryUD { get; set; }
        public decimal OrderQnt40HC { get; set; }
        public decimal FOBCostUSD { get; set; }
        public decimal GrossMarginAfterCommissionUSD { get; set; }
        public decimal ShippedQnt40HC { get; set; }
        public decimal ToBeShippedQnt40HC { get; set; }
        public string FactoryName { get; set; }
    }
}
