//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.ProductBreakDownPALMng.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProductBreakDownPALEntities : DbContext
    {
        public ProductBreakDownPALEntities()
            : base("name=ProductBreakDownPALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductBreakDownCategoryImagePAL> ProductBreakDownCategoryImagePAL { get; set; }
        public virtual DbSet<ProductBreakDownCategoryPAL> ProductBreakDownCategoryPAL { get; set; }
        public virtual DbSet<ProductBreakDownCategoryTypePAL> ProductBreakDownCategoryTypePAL { get; set; }
        public virtual DbSet<ProductBreakDownDefaultCategoryPAL> ProductBreakDownDefaultCategoryPAL { get; set; }
        public virtual DbSet<ProductBreakDownDetailPAL> ProductBreakDownDetailPAL { get; set; }
        public virtual DbSet<ProductBreakDownPAL> ProductBreakDownPAL { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ModelPAL_View> ProductBreakDownPAL_ModelPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_OptionToGetPricePAL_View> ProductBreakDownPAL_OptionToGetPricePAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_OptionToGetQuantityPAL_View> ProductBreakDownPAL_OptionToGetQuantityPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ProductBreakDownCalculationTypePAL_View> ProductBreakDownPAL_ProductBreakDownCalculationTypePAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ProductBreakDownCategoryAmountPAL_View> ProductBreakDownPAL_ProductBreakDownCategoryAmountPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ProductBreakDownCategoryImagePAL_View> ProductBreakDownPAL_ProductBreakDownCategoryImagePAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ProductBreakDownCategoryPAL_View> ProductBreakDownPAL_ProductBreakDownCategoryPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ProductBreakDownCategoryPercentPAL_View> ProductBreakDownPAL_ProductBreakDownCategoryPercentPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ProductBreakDownCategoryTypePAL_View> ProductBreakDownPAL_ProductBreakDownCategoryTypePAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ProductBreakDownDefaultCategoryPAL_View> ProductBreakDownPAL_ProductBreakDownDefaultCategoryPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ProductBreakDownDefaultCategoryPALSearchResult_View> ProductBreakDownPAL_ProductBreakDownDefaultCategoryPALSearchResult_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ProductBreakDownPAL_View> ProductBreakDownPAL_ProductBreakDownPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ProductBreakDownPALSearchResult_View> ProductBreakDownPAL_ProductBreakDownPALSearchResult_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_SampleProductPAL_View> ProductBreakDownPAL_SampleProductPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_SupportClientPAL_View> ProductBreakDownPAL_SupportClientPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_SupportModelPAL_View> ProductBreakDownPAL_SupportModelPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ProductBreakDownDetailPAL_View> ProductBreakDownPAL_ProductBreakDownDetailPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_SupportProductionItem_View> ProductBreakDownPAL_SupportProductionItem_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_SupportSampleProductPAL_View> ProductBreakDownPAL_SupportSampleProductPAL_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_SupportProduct_View> ProductBreakDownPAL_SupportProduct_View { get; set; }
        public virtual DbSet<ProductBreakDownPAL_SupportProductBreakDownCategoryPAL_View> ProductBreakDownPAL_SupportProductBreakDownCategoryPAL_View { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductBreakDownPAL_ModelDefaultOption_View> ProductBreakDownPAL_ModelDefaultOption_View { get; set; }
    
        public virtual ObjectResult<ProductBreakDownPAL_ProductBreakDownDefaultCategoryPALSearchResult_View> ProductBreakDownPAL_function_ProductBreakDownDefaultCategoryPALSearchResult(string defaultNameSearch, string defaultTypeSearch, string defaultUnitSearch, string sortedBy, string sortedDirection)
        {
            var defaultNameSearchParameter = defaultNameSearch != null ?
                new ObjectParameter("defaultNameSearch", defaultNameSearch) :
                new ObjectParameter("defaultNameSearch", typeof(string));
    
            var defaultTypeSearchParameter = defaultTypeSearch != null ?
                new ObjectParameter("defaultTypeSearch", defaultTypeSearch) :
                new ObjectParameter("defaultTypeSearch", typeof(string));
    
            var defaultUnitSearchParameter = defaultUnitSearch != null ?
                new ObjectParameter("defaultUnitSearch", defaultUnitSearch) :
                new ObjectParameter("defaultUnitSearch", typeof(string));
    
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("sortedBy", sortedBy) :
                new ObjectParameter("sortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("sortedDirection", sortedDirection) :
                new ObjectParameter("sortedDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_ProductBreakDownDefaultCategoryPALSearchResult_View>("ProductBreakDownPAL_function_ProductBreakDownDefaultCategoryPALSearchResult", defaultNameSearchParameter, defaultTypeSearchParameter, defaultUnitSearchParameter, sortedByParameter, sortedDirectionParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_ProductBreakDownDefaultCategoryPALSearchResult_View> ProductBreakDownPAL_function_ProductBreakDownDefaultCategoryPALSearchResult(string defaultNameSearch, string defaultTypeSearch, string defaultUnitSearch, string sortedBy, string sortedDirection, MergeOption mergeOption)
        {
            var defaultNameSearchParameter = defaultNameSearch != null ?
                new ObjectParameter("defaultNameSearch", defaultNameSearch) :
                new ObjectParameter("defaultNameSearch", typeof(string));
    
            var defaultTypeSearchParameter = defaultTypeSearch != null ?
                new ObjectParameter("defaultTypeSearch", defaultTypeSearch) :
                new ObjectParameter("defaultTypeSearch", typeof(string));
    
            var defaultUnitSearchParameter = defaultUnitSearch != null ?
                new ObjectParameter("defaultUnitSearch", defaultUnitSearch) :
                new ObjectParameter("defaultUnitSearch", typeof(string));
    
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("sortedBy", sortedBy) :
                new ObjectParameter("sortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("sortedDirection", sortedDirection) :
                new ObjectParameter("sortedDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_ProductBreakDownDefaultCategoryPALSearchResult_View>("ProductBreakDownPAL_function_ProductBreakDownDefaultCategoryPALSearchResult", mergeOption, defaultNameSearchParameter, defaultTypeSearchParameter, defaultUnitSearchParameter, sortedByParameter, sortedDirectionParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_ProductBreakDownPALSearchResult_View> ProductBreakDownPAL_function_ProductBreakDownPALSearchResult(string clientSearch, string modelSearch, string productSearch, string sampleSearch, string currencySearch, string sortedBy, string sortedDirection)
        {
            var clientSearchParameter = clientSearch != null ?
                new ObjectParameter("clientSearch", clientSearch) :
                new ObjectParameter("clientSearch", typeof(string));
    
            var modelSearchParameter = modelSearch != null ?
                new ObjectParameter("modelSearch", modelSearch) :
                new ObjectParameter("modelSearch", typeof(string));
    
            var productSearchParameter = productSearch != null ?
                new ObjectParameter("productSearch", productSearch) :
                new ObjectParameter("productSearch", typeof(string));
    
            var sampleSearchParameter = sampleSearch != null ?
                new ObjectParameter("sampleSearch", sampleSearch) :
                new ObjectParameter("sampleSearch", typeof(string));
    
            var currencySearchParameter = currencySearch != null ?
                new ObjectParameter("currencySearch", currencySearch) :
                new ObjectParameter("currencySearch", typeof(string));
    
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("sortedBy", sortedBy) :
                new ObjectParameter("sortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("sortedDirection", sortedDirection) :
                new ObjectParameter("sortedDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_ProductBreakDownPALSearchResult_View>("ProductBreakDownPAL_function_ProductBreakDownPALSearchResult", clientSearchParameter, modelSearchParameter, productSearchParameter, sampleSearchParameter, currencySearchParameter, sortedByParameter, sortedDirectionParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_ProductBreakDownPALSearchResult_View> ProductBreakDownPAL_function_ProductBreakDownPALSearchResult(string clientSearch, string modelSearch, string productSearch, string sampleSearch, string currencySearch, string sortedBy, string sortedDirection, MergeOption mergeOption)
        {
            var clientSearchParameter = clientSearch != null ?
                new ObjectParameter("clientSearch", clientSearch) :
                new ObjectParameter("clientSearch", typeof(string));
    
            var modelSearchParameter = modelSearch != null ?
                new ObjectParameter("modelSearch", modelSearch) :
                new ObjectParameter("modelSearch", typeof(string));
    
            var productSearchParameter = productSearch != null ?
                new ObjectParameter("productSearch", productSearch) :
                new ObjectParameter("productSearch", typeof(string));
    
            var sampleSearchParameter = sampleSearch != null ?
                new ObjectParameter("sampleSearch", sampleSearch) :
                new ObjectParameter("sampleSearch", typeof(string));
    
            var currencySearchParameter = currencySearch != null ?
                new ObjectParameter("currencySearch", currencySearch) :
                new ObjectParameter("currencySearch", typeof(string));
    
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("sortedBy", sortedBy) :
                new ObjectParameter("sortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("sortedDirection", sortedDirection) :
                new ObjectParameter("sortedDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_ProductBreakDownPALSearchResult_View>("ProductBreakDownPAL_function_ProductBreakDownPALSearchResult", mergeOption, clientSearchParameter, modelSearchParameter, productSearchParameter, sampleSearchParameter, currencySearchParameter, sortedByParameter, sortedDirectionParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_SupportClientPAL_View> ProductBreakDownPAL_function_SupportClientPAL(string clientSearch)
        {
            var clientSearchParameter = clientSearch != null ?
                new ObjectParameter("clientSearch", clientSearch) :
                new ObjectParameter("clientSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_SupportClientPAL_View>("ProductBreakDownPAL_function_SupportClientPAL", clientSearchParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_SupportClientPAL_View> ProductBreakDownPAL_function_SupportClientPAL(string clientSearch, MergeOption mergeOption)
        {
            var clientSearchParameter = clientSearch != null ?
                new ObjectParameter("clientSearch", clientSearch) :
                new ObjectParameter("clientSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_SupportClientPAL_View>("ProductBreakDownPAL_function_SupportClientPAL", mergeOption, clientSearchParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_SupportModelPAL_View> ProductBreakDownPAL_function_SupportModelPAL(string searchString, Nullable<int> userID)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_SupportModelPAL_View>("ProductBreakDownPAL_function_SupportModelPAL", searchStringParameter, userIDParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_SupportModelPAL_View> ProductBreakDownPAL_function_SupportModelPAL(string searchString, Nullable<int> userID, MergeOption mergeOption)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_SupportModelPAL_View>("ProductBreakDownPAL_function_SupportModelPAL", mergeOption, searchStringParameter, userIDParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_SupportSampleProductPAL_View> ProductBreakDownPAL_function_SupportSampleProductPAL(string searchString, string modelID, Nullable<int> userID)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var modelIDParameter = modelID != null ?
                new ObjectParameter("modelID", modelID) :
                new ObjectParameter("modelID", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_SupportSampleProductPAL_View>("ProductBreakDownPAL_function_SupportSampleProductPAL", searchStringParameter, modelIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_SupportSampleProductPAL_View> ProductBreakDownPAL_function_SupportSampleProductPAL(string searchString, string modelID, Nullable<int> userID, MergeOption mergeOption)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var modelIDParameter = modelID != null ?
                new ObjectParameter("modelID", modelID) :
                new ObjectParameter("modelID", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_SupportSampleProductPAL_View>("ProductBreakDownPAL_function_SupportSampleProductPAL", mergeOption, searchStringParameter, modelIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_SupportProductionItem_View> ProductBreakDownPAL_function_SupportProductionItemPAL(string searchString, string priceDate, Nullable<int> companyID)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var priceDateParameter = priceDate != null ?
                new ObjectParameter("priceDate", priceDate) :
                new ObjectParameter("priceDate", typeof(string));
    
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("companyID", companyID) :
                new ObjectParameter("companyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_SupportProductionItem_View>("ProductBreakDownPAL_function_SupportProductionItemPAL", searchStringParameter, priceDateParameter, companyIDParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_SupportProductionItem_View> ProductBreakDownPAL_function_SupportProductionItemPAL(string searchString, string priceDate, Nullable<int> companyID, MergeOption mergeOption)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var priceDateParameter = priceDate != null ?
                new ObjectParameter("priceDate", priceDate) :
                new ObjectParameter("priceDate", typeof(string));
    
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("companyID", companyID) :
                new ObjectParameter("companyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_SupportProductionItem_View>("ProductBreakDownPAL_function_SupportProductionItemPAL", mergeOption, searchStringParameter, priceDateParameter, companyIDParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_SupportProduct_View> ProductBreakDownPAL_function_SupportProductPAL(string searchString, string modelID, Nullable<int> userID)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var modelIDParameter = modelID != null ?
                new ObjectParameter("modelID", modelID) :
                new ObjectParameter("modelID", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_SupportProduct_View>("ProductBreakDownPAL_function_SupportProductPAL", searchStringParameter, modelIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<ProductBreakDownPAL_SupportProduct_View> ProductBreakDownPAL_function_SupportProductPAL(string searchString, string modelID, Nullable<int> userID, MergeOption mergeOption)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var modelIDParameter = modelID != null ?
                new ObjectParameter("modelID", modelID) :
                new ObjectParameter("modelID", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductBreakDownPAL_SupportProduct_View>("ProductBreakDownPAL_function_SupportProductPAL", mergeOption, searchStringParameter, modelIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<MasterExchangeRateMng_function_GetExchangeRate_Result> MasterExchangeRateMng_function_GetExchangeRate(Nullable<System.DateTime> inputDate, string currency)
        {
            var inputDateParameter = inputDate.HasValue ?
                new ObjectParameter("InputDate", inputDate) :
                new ObjectParameter("InputDate", typeof(System.DateTime));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("Currency", currency) :
                new ObjectParameter("Currency", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MasterExchangeRateMng_function_GetExchangeRate_Result>("MasterExchangeRateMng_function_GetExchangeRate", inputDateParameter, currencyParameter);
        }
    }
}
