//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.ProductBreakDownPALMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBreakDownPAL_ModelDefaultOption_View
    {
        public int ModelID { get; set; }
        public string ModelUD { get; set; }
        public string ModelNM { get; set; }
        public Nullable<int> FrameMaterialID { get; set; }
        public Nullable<int> FrameMaterialColorID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<int> MaterialTypeID { get; set; }
        public Nullable<int> MaterialColorID { get; set; }
        public Nullable<int> SubMaterialID { get; set; }
        public Nullable<int> SubMaterialColorID { get; set; }
        public Nullable<int> SeatCushionID { get; set; }
        public Nullable<int> BackCushionID { get; set; }
        public Nullable<int> CushionColorID { get; set; }
        public Nullable<int> ManufacturerCountryID { get; set; }
        public Nullable<int> FSCTypeID { get; set; }
        public Nullable<int> FSCPercentID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ArticleCode { get; set; }
        public string Description { get; set; }
    }
}
