//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.CostInvoiceMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostInvoiceDetail
    {
        public CostInvoiceDetail()
        {
            this.CostInvoiceDetailExtend = new HashSet<CostInvoiceDetailExtend>();
        }
    
        public int CostInvoiceDetailID { get; set; }
        public string Description { get; set; }
        public Nullable<int> LoadingPlanID { get; set; }
        public string CostType { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual CostInvoice CostInvoice { get; set; }
        public virtual ICollection<CostInvoiceDetailExtend> CostInvoiceDetailExtend { get; set; }
    }
}
