//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.CashBookReceiptMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBookMng_CashBookPaidBy_View
    {
        public int CashBookPaidByID { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatorName { get; set; }
        public Nullable<decimal> VNDAmount { get; set; }
        public Nullable<int> BalanceMonth { get; set; }
        public Nullable<int> BalanceYear { get; set; }
    }
}
