//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.NotificationMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationMng_NotificationUser_View
    {
        public long PrimaryID { get; set; }
        public Nullable<int> Id { get; set; }
        public string Value { get; set; }
        public string Label { get; set; }
        public string EmployeeEmail { get; set; }
        public string EmployeeNM { get; set; }
        public string FullName { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
