//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.TransportInvoice.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportInvoiceMng_TransportInvoice_View
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportInvoiceMng_TransportInvoice_View()
        {
            this.TransportInvoiceMng_TransportInvoiceDetail_View = new HashSet<TransportInvoiceMng_TransportInvoiceDetail_View>();
        }
    
        public int TransportInvoiceID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> BookingID { get; set; }
        public string Currency { get; set; }
        public string RefNo { get; set; }
        public string Remark { get; set; }
        public Nullable<int> InvoiceStatusID { get; set; }
        public Nullable<int> StatusUpdatedBy { get; set; }
        public Nullable<System.DateTime> StatusUpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ForwarderID { get; set; }
        public string CreatorName { get; set; }
        public string UpdatorName { get; set; }
        public string StatustorName { get; set; }
        public string BLNo { get; set; }
        public string ForwarderNM { get; set; }
        public string InvoiceStatusText { get; set; }
        public string PoLname { get; set; }
        public string PoDName { get; set; }
        public string ETD { get; set; }
        public string ETA { get; set; }
        public string ClientUD { get; set; }
        public string ClientNM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportInvoiceMng_TransportInvoiceDetail_View> TransportInvoiceMng_TransportInvoiceDetail_View { get; set; }
    }
}
