//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ECommercialInvoiceMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECommercialInvoiceMng_ContainerTransport_View
    {
        public int LoadingPlanID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public string ContainerNo { get; set; }
        public string ContainerTypeNM { get; set; }
        public Nullable<int> ContainerTypeID { get; set; }
        public string ETD { get; set; }
    
        public virtual ECommercialInvoiceMng_BillTransport_View ECommercialInvoiceMng_BillTransport_View { get; set; }
    }
}
