//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.FactoryOrderNorm.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FactoryOrderNormEntities : DbContext
    {
        public FactoryOrderNormEntities()
            : base("name=FactoryOrderNormEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FactoryMaterialOrderNorm> FactoryMaterialOrderNorm { get; set; }
        public virtual DbSet<FactoryOrderNorm> FactoryOrderNorm { get; set; }
        public virtual DbSet<FactoryOrderNormMng_FactoryMaterialOrderNorm_View> FactoryOrderNormMng_FactoryMaterialOrderNorm_View { get; set; }
        public virtual DbSet<FactoryOrderNormMng_FactoryOrderNorm_SearchView> FactoryOrderNormMng_FactoryOrderNorm_SearchView { get; set; }
        public virtual DbSet<FactoryOrderNormMng_FactoryOrderNorm_View> FactoryOrderNormMng_FactoryOrderNorm_View { get; set; }
        public virtual DbSet<FactoryOrderNormMng_FactoryFinishedProductOrderNorm_View> FactoryOrderNormMng_FactoryFinishedProductOrderNorm_View { get; set; }
        public virtual DbSet<FactoryFinishedProduct> FactoryFinishedProduct { get; set; }
        public virtual DbSet<FactoryFinishedProductOrderNorm> FactoryFinishedProductOrderNorm { get; set; }
        public virtual DbSet<FactoryOrderNormMng_Client_View> FactoryOrderNormMng_Client_View { get; set; }
        public virtual DbSet<FactoryOrderNormMng_ClientProduct_View> FactoryOrderNormMng_ClientProduct_View { get; set; }
        public virtual DbSet<FactoryOrderNormMng_FactoryFinishedProductNorm_View> FactoryOrderNormMng_FactoryFinishedProductNorm_View { get; set; }
        public virtual DbSet<FactoryOrderNormMng_FactoryMaterialNorm_View> FactoryOrderNormMng_FactoryMaterialNorm_View { get; set; }
        public virtual DbSet<FactoryOrderNormMng_Product_View> FactoryOrderNormMng_Product_View { get; set; }
        public virtual DbSet<FactoryFinishedProductOrderNormFactoryGoodsProcedure> FactoryFinishedProductOrderNormFactoryGoodsProcedure { get; set; }
        public virtual DbSet<FactoryOrderNormMng_FactoryFinishedProductOrderNormFactoryGoodsProcedure_View> FactoryOrderNormMng_FactoryFinishedProductOrderNormFactoryGoodsProcedure_View { get; set; }
        public virtual DbSet<FactoryOrderNormMng_FactoryFinishedProductNormFactoryGoodsProcedure_View> FactoryOrderNormMng_FactoryFinishedProductNormFactoryGoodsProcedure_View { get; set; }
    
        public virtual ObjectResult<FactoryOrderNormMng_FactoryOrderNorm_SearchView> FactoryOrderNormMng_function_SearchFactoryOrderNorm(string sortedBy, string sortedDirection, string articleCode, string description, string clientUD, string season)
        {
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            var articleCodeParameter = articleCode != null ?
                new ObjectParameter("ArticleCode", articleCode) :
                new ObjectParameter("ArticleCode", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var clientUDParameter = clientUD != null ?
                new ObjectParameter("ClientUD", clientUD) :
                new ObjectParameter("ClientUD", typeof(string));
    
            var seasonParameter = season != null ?
                new ObjectParameter("Season", season) :
                new ObjectParameter("Season", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryOrderNormMng_FactoryOrderNorm_SearchView>("FactoryOrderNormMng_function_SearchFactoryOrderNorm", sortedByParameter, sortedDirectionParameter, articleCodeParameter, descriptionParameter, clientUDParameter, seasonParameter);
        }
    
        public virtual ObjectResult<FactoryOrderNormMng_FactoryOrderNorm_SearchView> FactoryOrderNormMng_function_SearchFactoryOrderNorm(string sortedBy, string sortedDirection, string articleCode, string description, string clientUD, string season, MergeOption mergeOption)
        {
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            var articleCodeParameter = articleCode != null ?
                new ObjectParameter("ArticleCode", articleCode) :
                new ObjectParameter("ArticleCode", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var clientUDParameter = clientUD != null ?
                new ObjectParameter("ClientUD", clientUD) :
                new ObjectParameter("ClientUD", typeof(string));
    
            var seasonParameter = season != null ?
                new ObjectParameter("Season", season) :
                new ObjectParameter("Season", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryOrderNormMng_FactoryOrderNorm_SearchView>("FactoryOrderNormMng_function_SearchFactoryOrderNorm", mergeOption, sortedByParameter, sortedDirectionParameter, articleCodeParameter, descriptionParameter, clientUDParameter, seasonParameter);
        }
    
        public virtual ObjectResult<FactoryOrderNormMng_Client_View> FactoryOrderNormMng_function_SearchClient(string sortedBy, string sortedDirection, string clientUD, string articleCode, string description)
        {
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            var clientUDParameter = clientUD != null ?
                new ObjectParameter("ClientUD", clientUD) :
                new ObjectParameter("ClientUD", typeof(string));
    
            var articleCodeParameter = articleCode != null ?
                new ObjectParameter("ArticleCode", articleCode) :
                new ObjectParameter("ArticleCode", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryOrderNormMng_Client_View>("FactoryOrderNormMng_function_SearchClient", sortedByParameter, sortedDirectionParameter, clientUDParameter, articleCodeParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<FactoryOrderNormMng_Client_View> FactoryOrderNormMng_function_SearchClient(string sortedBy, string sortedDirection, string clientUD, string articleCode, string description, MergeOption mergeOption)
        {
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            var clientUDParameter = clientUD != null ?
                new ObjectParameter("ClientUD", clientUD) :
                new ObjectParameter("ClientUD", typeof(string));
    
            var articleCodeParameter = articleCode != null ?
                new ObjectParameter("ArticleCode", articleCode) :
                new ObjectParameter("ArticleCode", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryOrderNormMng_Client_View>("FactoryOrderNormMng_function_SearchClient", mergeOption, sortedByParameter, sortedDirectionParameter, clientUDParameter, articleCodeParameter, descriptionParameter);
        }
    }
}
