//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.Sample3Mng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample3Mng_SampleOrder_View
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sample3Mng_SampleOrder_View()
        {
            this.Sample3Mng_SampleMonitor_View = new HashSet<Sample3Mng_SampleMonitor_View>();
        }
    
        public int SampleOrderID { get; set; }
        public string SampleOrderUD { get; set; }
        public string Season { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> HardDeadline { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> TransportTypeID { get; set; }
        public Nullable<int> PurposeID { get; set; }
        public Nullable<int> SampleOrderStatusID { get; set; }
        public string Destination { get; set; }
        public string Remark { get; set; }
        public string NotifyEmail { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> StatusUpdatedBy { get; set; }
        public Nullable<System.DateTime> StatusUpdatedDate { get; set; }
        public string CreatorName { get; set; }
        public string UpdatorName { get; set; }
        public string ClientUD { get; set; }
        public string SampleOrderStatusNM { get; set; }
        public string TransportTypeNM { get; set; }
        public string PurposeNM { get; set; }
        public string ClientNM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sample3Mng_SampleMonitor_View> Sample3Mng_SampleMonitor_View { get; set; }
    }
}
