//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.Sample3Mng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample3Mng_SampleOrderOverview_Product_View
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sample3Mng_SampleOrderOverview_Product_View()
        {
            this.Sample3Mng_SampleOrderOverview_ProductLocation_View = new HashSet<Sample3Mng_SampleOrderOverview_ProductLocation_View>();
            this.Sample3Mng_SampleOrderOverview_ProductSubFactory_View = new HashSet<Sample3Mng_SampleOrderOverview_ProductSubFactory_View>();
        }
    
        public int SampleProductID { get; set; }
        public string SampleProductUD { get; set; }
        public string SampleProductStatusNM { get; set; }
        public string ArticleDescription { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> IsTDNeeded { get; set; }
        public Nullable<System.DateTime> FactoryDeadline { get; set; }
        public Nullable<int> QARemarkUpdatedBy { get; set; }
        public string QARemarkUpdatorName { get; set; }
        public Nullable<System.DateTime> QARemarkUpdatedDate { get; set; }
        public string VNSuggestedFactoryUD { get; set; }
        public Nullable<decimal> IndicatedPrice { get; set; }
        public string ThumbnailLocation { get; set; }
        public string FileLocation { get; set; }
        public string FinishedImageThumbnailLocation { get; set; }
        public string FinishedImageFileLocation { get; set; }
        public Nullable<int> SampleOrderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sample3Mng_SampleOrderOverview_ProductLocation_View> Sample3Mng_SampleOrderOverview_ProductLocation_View { get; set; }
        public virtual Sample3Mng_SampleOrderOverview_Order_View Sample3Mng_SampleOrderOverview_Order_View { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sample3Mng_SampleOrderOverview_ProductSubFactory_View> Sample3Mng_SampleOrderOverview_ProductSubFactory_View { get; set; }
    }
}
