//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.DashboardMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoardMng_SampleProduct_View
    {
        public int SampleProductID { get; set; }
        public Nullable<int> SampleOrderID { get; set; }
        public string SampleProductUD { get; set; }
        public string DisplayText { get; set; }
    
        public virtual DashBoardMng_SampleOrder_View DashBoardMng_SampleOrder_View { get; set; }
    }
}
