//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.Booking2Mng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking2Mng_BookingPlanningFactoryOrder_View
    {
        public long KeyID { get; set; }
        public Nullable<int> FactoryOrderID { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> PlannedQnt { get; set; }
        public Nullable<int> OrderQnt { get; set; }
        public string ProformaInvoiceNo { get; set; }
        public string FactoryOrderUD { get; set; }
        public Nullable<System.DateTime> LDS { get; set; }
        public string FactoryUD { get; set; }
        public Nullable<int> ShippedQnt { get; set; }
    
        public virtual Booking2Mng_Booking_View Booking2Mng_Booking_View { get; set; }
    }
}
