//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.PurchasingCreditNote.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasingInvoice_View
    {
        public PurchasingInvoice_View()
        {
            this.PurchasingInvoiceDetail_View = new HashSet<PurchasingInvoiceDetail_View>();
            this.PurchasingInvoiceSparepartDetail_View = new HashSet<PurchasingInvoiceSparepartDetail_View>();
        }
    
        public int PurchasingInvoiceID { get; set; }
        public string InvoiceNo { get; set; }
        public string FactoryInvoiceNo { get; set; }
        public string BLNo { get; set; }
        public Nullable<System.DateTime> ShipedDate { get; set; }
        public string SupplierNM { get; set; }
        public string ForwarderNM { get; set; }
        public string Feeder { get; set; }
        public string POLName { get; set; }
        public string PODName { get; set; }
        public string Season { get; set; }
        public Nullable<int> SupplierID { get; set; }
    
        public virtual ICollection<PurchasingInvoiceDetail_View> PurchasingInvoiceDetail_View { get; set; }
        public virtual ICollection<PurchasingInvoiceSparepartDetail_View> PurchasingInvoiceSparepartDetail_View { get; set; }
    }
}
