//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.WarehouseImportMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseImportMng_WarehouseImport_View
    {
        public WarehouseImportMng_WarehouseImport_View()
        {
            this.WarehouseImportMng_WarehouseImportProductDetail_View = new HashSet<WarehouseImportMng_WarehouseImportProductDetail_View>();
            this.WarehouseImportMng_WarehouseImportSparepartDetail_View = new HashSet<WarehouseImportMng_WarehouseImportSparepartDetail_View>();
        }
    
        public int WarehouseImportID { get; set; }
        public string ReceiptNo { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> ImportedDate { get; set; }
        public Nullable<int> ImportTypeID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public byte[] ConcurrencyFlag { get; set; }
        public string UpdatorName { get; set; }
        public string ConfirmerName { get; set; }
        public string ImportTypeNM { get; set; }
        public string Season { get; set; }
        public Nullable<int> ECommercialInvoiceID { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
        public Nullable<System.DateTime> ContainerReceivedDate { get; set; }
        public Nullable<System.DateTime> ContainerReceivedTime { get; set; }
        public Nullable<bool> IsWexImported { get; set; }
    
        public virtual ICollection<WarehouseImportMng_WarehouseImportProductDetail_View> WarehouseImportMng_WarehouseImportProductDetail_View { get; set; }
        public virtual ICollection<WarehouseImportMng_WarehouseImportSparepartDetail_View> WarehouseImportMng_WarehouseImportSparepartDetail_View { get; set; }
    }
}
