//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.WarehouseImportMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseImportMng_OnSeaSparepart_View
    {
        public int LoadingPlanSparepartDetailID { get; set; }
        public Nullable<int> SparepartID { get; set; }
        public Nullable<int> ProductStatusID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ArticleCode { get; set; }
        public string Description { get; set; }
        public string ProductStatusNM { get; set; }
        public string ClientUD { get; set; }
        public string ClientNM { get; set; }
        public string ProformaInvoiceNo { get; set; }
        public string FactoryUD { get; set; }
        public string BLNo { get; set; }
        public string ContainerNo { get; set; }
        public string ContainerTypeNM { get; set; }
        public string SealNo { get; set; }
    }
}
