//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.PackingListMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingListMng_PackingList_SearchView
    {
        public PackingListMng_PackingList_SearchView()
        {
            this.PackingListMng_PackingList_SearchContainerNoView = new HashSet<PackingListMng_PackingList_SearchContainerNoView>();
        }
    
        public int PackingListID { get; set; }
        public string PackingListUD { get; set; }
        public Nullable<System.DateTime> PackingListDate { get; set; }
        public string DescriptionOfGoods { get; set; }
        public string ContainerRemark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string InvoiceNo { get; set; }
        public string BLNo { get; set; }
        public string PODName { get; set; }
        public string POLName { get; set; }
        public string CreatorName { get; set; }
        public string UpdatorName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string SupplierUD { get; set; }
        public string SupplierNM { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<int> UpdatorID { get; set; }
    
        public virtual ICollection<PackingListMng_PackingList_SearchContainerNoView> PackingListMng_PackingList_SearchContainerNoView { get; set; }
    }
}
