//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.DraftPackingListMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftPackingListDetail
    {
        public int DraftPackingListDetailID { get; set; }
        public Nullable<int> DraftPackingListID { get; set; }
        public Nullable<int> DraftCommercialInvoiceDetailID { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PKGs { get; set; }
        public Nullable<decimal> NettWeight { get; set; }
        public Nullable<decimal> KGs { get; set; }
        public Nullable<decimal> CBMs { get; set; }
        public string Remark { get; set; }
    
        public virtual DraftPackingList DraftPackingList { get; set; }
    }
}
