//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ModelMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageGallery
    {
        public ImageGallery()
        {
            this.ImageGalleryVersion = new HashSet<ImageGalleryVersion>();
        }
    
        public int ImageGalleryID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string FileUD { get; set; }
        public Nullable<int> GalleryItemTypeID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string Description { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Season { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<int> MaterialTypeID { get; set; }
        public Nullable<int> MaterialColorID { get; set; }
        public Nullable<int> BackCushionID { get; set; }
        public Nullable<int> SeatCushionID { get; set; }
        public Nullable<int> CushionColorID { get; set; }
        public Nullable<bool> IsNewProduct { get; set; }
        public Nullable<bool> IsProductDefault { get; set; }
        public byte[] ConcurrencyFlag { get; set; }
        public Nullable<int> SeasonTypeID { get; set; }
        public Nullable<System.DateTime> SampleImportDate { get; set; }
        public string SampleImportBy { get; set; }
        public Nullable<bool> IsFinalized { get; set; }
        public string TempDescription { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsUsedForWarehouseConnect { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual ICollection<ImageGalleryVersion> ImageGalleryVersion { get; set; }
        public virtual Model Model { get; set; }
    }
}
