//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.SupplierMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierBank
    {
        public int SupplierBankID { get; set; }
        public string BankCode { get; set; }
        public string BankNM { get; set; }
        public string AccountNM { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SupplierID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
