//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.Sample2Mng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleTechnicalDrawing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SampleTechnicalDrawing()
        {
            this.SampleTechnicalDrawingFile = new HashSet<SampleTechnicalDrawingFile>();
        }
    
        public int SampleTechnicalDrawingID { get; set; }
        public Nullable<int> SampleProductID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public string SourceFileUD { get; set; }
        public string PreviewFileUD { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual SampleProduct SampleProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleTechnicalDrawingFile> SampleTechnicalDrawingFile { get; set; }
    }
}
