//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.PurchaseOrderTrackingRpt.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderTrackingRpt_SupportProductionItemGroup_View
    {
        public int ItemGroupID { get; set; }
        public string ItemGroupUD { get; set; }
        public string ItemGroupNM { get; set; }
    }
}
