//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.OfferSeasonMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferSeasonMng_Sparepart_View
    {
        public int SparepartID { get; set; }
        public string ModelUD { get; set; }
        public string ModelNM { get; set; }
        public string Season { get; set; }
        public string ArticleCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> PartID { get; set; }
    }
}
