//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.ClientOfferMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCostItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientCostItem()
        {
            this.ClientOfferCostDetail = new HashSet<ClientOfferCostDetail>();
        }
    
        public int ClientCostItemID { get; set; }
        public string ClientCostItemNM { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ClientCostTypeID { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> ClientCostChargeTypeID { get; set; }
        public Nullable<int> POLID { get; set; }
    
        public virtual POL POL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOfferCostDetail> ClientOfferCostDetail { get; set; }
    }
}
