//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.BackCushionMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackCushionMng_BackCushionProductGroup_View
    {
        public int BackCushionProductGroupID { get; set; }
        public Nullable<int> BackCushionID { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string ProductGroupNM { get; set; }
    
        public virtual BackCushionMng_BackCushion_View BackCushionMng_BackCushion_View { get; set; }
    }
}
