//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.CushionMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class CushionMng_CushionSearchResult_View
    {
        public int CushionID { get; set; }
        public string CushionUD { get; set; }
        public string CushionNM { get; set; }
        public string Season { get; set; }
        public Nullable<bool> IsStandard { get; set; }
        public string UpdatorName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
        public string ImageFile_DisplayUrl { get; set; }
        public string ImageFile_FullSizeUrl { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
