//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.BOMStandardMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMStandardMng_ProductionItem_View
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOMStandardMng_ProductionItem_View()
        {
            this.BOMStandardMng_ProductionItemUnit_View = new HashSet<BOMStandardMng_ProductionItemUnit_View>();
        }
    
        public int ProductionItemID { get; set; }
        public string ProductionItemUD { get; set; }
        public string ProductionItemNM { get; set; }
        public Nullable<int> ProductionItemTypeID { get; set; }
        public string Unit { get; set; }
        public string ProductionItemTypeNM { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string UnitNM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOMStandardMng_ProductionItemUnit_View> BOMStandardMng_ProductionItemUnit_View { get; set; }
    }
}
