//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.PriceListClientCharge.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListClientCharge_PriceListClientChargeSearch_View
    {
        public int PriceListClientChargeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientUD { get; set; }
        public string ClientNM { get; set; }
        public Nullable<int> ChargeTypeID { get; set; }
        public string ChargeTypeNM { get; set; }
        public Nullable<int> CurrencyTypeID { get; set; }
        public string CurrencyTypeNM { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreateFullName { get; set; }
        public string CreateEmployeeNM { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdateFullName { get; set; }
        public string UpdateEmployeeNM { get; set; }
    }
}
