//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.AVFPurchasingInvoiceMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVFPurchasingInvoiceMng_AVFPurchasingInvoice_View
    {
        public AVFPurchasingInvoiceMng_AVFPurchasingInvoice_View()
        {
            this.AVFPurchasingInvoiceMng_AVFPurchasingInvoiceDetail_View = new HashSet<AVFPurchasingInvoiceMng_AVFPurchasingInvoiceDetail_View>();
        }
    
        public int AVFPurchasingInvoiceID { get; set; }
        public string AVFPurchasingInvoiceUD { get; set; }
        public Nullable<int> AVFSupplierID { get; set; }
        public string SerialNo { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string ContainerTransportation { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Season { get; set; }
        public int TaxRate { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] ConcurrencyFlag { get; set; }
        public string Remark { get; set; }
        public string PDFFileScan { get; set; }
        public string AVFSupplierNM { get; set; }
        public string AVFSupplierUD { get; set; }
        public string FriendlyName { get; set; }
        public string FileLocation { get; set; }
        public string CreatorName { get; set; }
        public string UpdatorName { get; set; }
        public string CreatorName2 { get; set; }
        public string UpdatorName2 { get; set; }
    
        public virtual ICollection<AVFPurchasingInvoiceMng_AVFPurchasingInvoiceDetail_View> AVFPurchasingInvoiceMng_AVFPurchasingInvoiceDetail_View { get; set; }
    }
}
