//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.OrderQuantityCheckingRpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderQuantityCheckingRpt_FactoryOrderDetail_View
    {
        public int FactoryOrderDetailID { get; set; }
        public string FactoryOrderUD { get; set; }
        public string FactoryUD { get; set; }
        public Nullable<int> OrderQnt { get; set; }
        public Nullable<int> SaleOrderDetailID { get; set; }
    
        public virtual OrderQuantityCheckingRpt_SaleOrderDetail_View OrderQuantityCheckingRpt_SaleOrderDetail_View { get; set; }
    }
}
