//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.QuotationMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationMng_FactoryOrderSearchResult_View
    {
        public int FactoryOrderID { get; set; }
        public string Season { get; set; }
        public string FactoryOrderUD { get; set; }
        public Nullable<System.DateTime> LDS { get; set; }
        public string FactoryUD { get; set; }
        public Nullable<int> FactoryID { get; set; }
        public string ProductionStatus { get; set; }
    }
}
