//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.BreakDownMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakdownMng_LoadDetailCalculationPriceMangementCost_View
    {
        public long KeyID { get; set; }
        public Nullable<int> BreakdownCategoryOptionID { get; set; }
        public Nullable<int> BreakdownID { get; set; }
        public Nullable<int> BreakdownCategoryID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<decimal> QuantityPercent { get; set; }
        public long PrimaryID { get; set; }
    }
}
