//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.BreakDownMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakdownCategoryOptionImage
    {
        public int BreakdownCategoryOptionImageID { get; set; }
        public Nullable<int> BreakdownCategoryOptionID { get; set; }
        public string FileUD { get; set; }
        public string Description { get; set; }
    
        public virtual BreakdownCategoryOption BreakdownCategoryOption { get; set; }
    }
}
