//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.BreakDownMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakdownMng_ClientSpecialPackagingMethod_View
    {
        public int ClientSpecialPackagingMethodID { get; set; }
        public string ClientSpecialPackagingMethodNM { get; set; }
        public string ClientUD { get; set; }
    }
}
