//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.MISaleByMaterialRpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISaleByMaterialRpt_AllMaterial_ProformaInvoice_View
    {
        public long PrimaryID { get; set; }
        public string MaterialNM { get; set; }
        public Nullable<decimal> TotalCont { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Season { get; set; }
    }
}
