//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.GrossMarginSummaryRpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrossMarginSummaryRpt_GrossMarginSummaryHtml_View
    {
        public long PrimaryID { get; set; }
        public string ClientUD { get; set; }
        public string ClientNM { get; set; }
        public string SaleUD { get; set; }
        public Nullable<decimal> NetAmountEUR { get; set; }
        public Nullable<decimal> CostAmountEUR { get; set; }
        public Nullable<decimal> CommAmountEUR { get; set; }
        public Nullable<decimal> GrossMarginBeforeEUR { get; set; }
        public Nullable<decimal> GrossMarginBeforePercent { get; set; }
        public Nullable<decimal> GrossMarginAfterCommEUR { get; set; }
        public Nullable<decimal> GrossMarginAfterCommPercent { get; set; }
        public Nullable<decimal> GrossMarginAfterCommAndCreditNoteEUR { get; set; }
        public Nullable<decimal> GrossMarginAfterCommAndCreditNotePercent { get; set; }
        public Nullable<decimal> CreditNoteAmountEUR { get; set; }
    }
}
