//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.FactoryProductionStatus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryProductionStatusMng_FactoryProductionStatus_SearchView
    {
        public int FactoryProductionStatusID { get; set; }
        public Nullable<int> FactoryID { get; set; }
        public string Season { get; set; }
        public Nullable<int> WeekNo { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatorName { get; set; }
        public Nullable<decimal> FactoryCapacity { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string FactoryUD { get; set; }
    }
}
