//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.SaleOrderMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderMng_SaleOrder_ReportView
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleOrderMng_SaleOrder_ReportView()
        {
            this.SaleOrderMng_SaleOrderDetailSparepart_ReportView = new HashSet<SaleOrderMng_SaleOrderDetailSparepart_ReportView>();
            this.SaleOrderMng_SaleOrderDetail_ReportView = new HashSet<SaleOrderMng_SaleOrderDetail_ReportView>();
            this.SaleOrderMng_SaleOrderExtend_ReportView = new HashSet<SaleOrderMng_SaleOrderExtend_ReportView>();
        }
    
        public int SaleOrderID { get; set; }
        public string ClientNM { get; set; }
        public string ClientAddress { get; set; }
        public string ZipCode_City { get; set; }
        public string ClientCountryNM { get; set; }
        public string InvoiceDate { get; set; }
        public string ProformaInvoiceNo { get; set; }
        public string ClientUD { get; set; }
        public string VATNo { get; set; }
        public Nullable<int> TotalQnt { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public decimal VATPercent { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string Reference { get; set; }
        public string PaymentTermNM { get; set; }
        public string DeliveryTermNM { get; set; }
        public string Conditions { get; set; }
        public string SaleNM { get; set; }
        public Nullable<bool> IsViewQuantityContOnPrintout { get; set; }
        public Nullable<bool> IsViewDeliveryDateOnPrintout { get; set; }
        public Nullable<bool> IsViewLDSOnPrintout { get; set; }
        public Nullable<int> Quantity20DC { get; set; }
        public Nullable<int> Quantity40DC { get; set; }
        public Nullable<int> Quantity40HC { get; set; }
        public string LDS { get; set; }
        public string DeliveryDate { get; set; }
        public string ClientOrderNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderMng_SaleOrderDetailSparepart_ReportView> SaleOrderMng_SaleOrderDetailSparepart_ReportView { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderMng_SaleOrderDetail_ReportView> SaleOrderMng_SaleOrderDetail_ReportView { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderMng_SaleOrderExtend_ReportView> SaleOrderMng_SaleOrderExtend_ReportView { get; set; }
    }
}
