//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FactoryProformaInvoiceMng
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FactoryProformaInvoiceMngEntities : DbContext
    {
        public FactoryProformaInvoiceMngEntities()
            : base("name=FactoryProformaInvoiceMngEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FactoryProformaInvoice> FactoryProformaInvoice { get; set; }
        public virtual DbSet<FactoryProformaInvoiceDetail> FactoryProformaInvoiceDetail { get; set; }
        public virtual DbSet<FactoryProformaInvoiceMng_FactoryProformaInvoice_View> FactoryProformaInvoiceMng_FactoryProformaInvoice_View { get; set; }
        public virtual DbSet<FactoryProformaInvoiceMng_FactoryProformaInvoiceDetail_View> FactoryProformaInvoiceMng_FactoryProformaInvoiceDetail_View { get; set; }
        public virtual DbSet<FactoryProformaInvoiceMng_FactoryProformaInvoiceSearchResult_View> FactoryProformaInvoiceMng_FactoryProformaInvoiceSearchResult_View { get; set; }
        public virtual DbSet<FactoryProformaInvoiceMng_FactoryOrderItemSearchResult_View> FactoryProformaInvoiceMng_FactoryOrderItemSearchResult_View { get; set; }
        public virtual DbSet<FactoryProformaInvoiceMng_FactoryOrderSearchResult_View> FactoryProformaInvoiceMng_FactoryOrderSearchResult_View { get; set; }
        public virtual DbSet<FactoryProformaInvoiceMng_FactoryOrderInfo_View> FactoryProformaInvoiceMng_FactoryOrderInfo_View { get; set; }
    
        public virtual ObjectResult<FactoryProformaInvoiceMng_FactoryOrderItemSearchResult_View> FactoryProformaInvoiceMng_function_QuickSearchFactoryOrderItem(string articleCode, string description, string factoryOrderUD, string clientUD, string season, Nullable<int> factoryID, string sortedBy, string sortedDirection)
        {
            var articleCodeParameter = articleCode != null ?
                new ObjectParameter("ArticleCode", articleCode) :
                new ObjectParameter("ArticleCode", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var factoryOrderUDParameter = factoryOrderUD != null ?
                new ObjectParameter("FactoryOrderUD", factoryOrderUD) :
                new ObjectParameter("FactoryOrderUD", typeof(string));
    
            var clientUDParameter = clientUD != null ?
                new ObjectParameter("ClientUD", clientUD) :
                new ObjectParameter("ClientUD", typeof(string));
    
            var seasonParameter = season != null ?
                new ObjectParameter("Season", season) :
                new ObjectParameter("Season", typeof(string));
    
            var factoryIDParameter = factoryID.HasValue ?
                new ObjectParameter("FactoryID", factoryID) :
                new ObjectParameter("FactoryID", typeof(int));
    
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryProformaInvoiceMng_FactoryOrderItemSearchResult_View>("FactoryProformaInvoiceMng_function_QuickSearchFactoryOrderItem", articleCodeParameter, descriptionParameter, factoryOrderUDParameter, clientUDParameter, seasonParameter, factoryIDParameter, sortedByParameter, sortedDirectionParameter);
        }
    
        public virtual ObjectResult<FactoryProformaInvoiceMng_FactoryOrderItemSearchResult_View> FactoryProformaInvoiceMng_function_QuickSearchFactoryOrderItem(string articleCode, string description, string factoryOrderUD, string clientUD, string season, Nullable<int> factoryID, string sortedBy, string sortedDirection, MergeOption mergeOption)
        {
            var articleCodeParameter = articleCode != null ?
                new ObjectParameter("ArticleCode", articleCode) :
                new ObjectParameter("ArticleCode", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var factoryOrderUDParameter = factoryOrderUD != null ?
                new ObjectParameter("FactoryOrderUD", factoryOrderUD) :
                new ObjectParameter("FactoryOrderUD", typeof(string));
    
            var clientUDParameter = clientUD != null ?
                new ObjectParameter("ClientUD", clientUD) :
                new ObjectParameter("ClientUD", typeof(string));
    
            var seasonParameter = season != null ?
                new ObjectParameter("Season", season) :
                new ObjectParameter("Season", typeof(string));
    
            var factoryIDParameter = factoryID.HasValue ?
                new ObjectParameter("FactoryID", factoryID) :
                new ObjectParameter("FactoryID", typeof(int));
    
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryProformaInvoiceMng_FactoryOrderItemSearchResult_View>("FactoryProformaInvoiceMng_function_QuickSearchFactoryOrderItem", mergeOption, articleCodeParameter, descriptionParameter, factoryOrderUDParameter, clientUDParameter, seasonParameter, factoryIDParameter, sortedByParameter, sortedDirectionParameter);
        }
    
        public virtual ObjectResult<FactoryProformaInvoiceMng_FactoryProformaInvoiceSearchResult_View> FactoryProformaInvoiceMng_function_SearchFactoryProformaInvoice(string factoryUD, string proformaInvoiceNo, string season, string sortedBy, string sortedDirection)
        {
            var factoryUDParameter = factoryUD != null ?
                new ObjectParameter("FactoryUD", factoryUD) :
                new ObjectParameter("FactoryUD", typeof(string));
    
            var proformaInvoiceNoParameter = proformaInvoiceNo != null ?
                new ObjectParameter("ProformaInvoiceNo", proformaInvoiceNo) :
                new ObjectParameter("ProformaInvoiceNo", typeof(string));
    
            var seasonParameter = season != null ?
                new ObjectParameter("Season", season) :
                new ObjectParameter("Season", typeof(string));
    
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryProformaInvoiceMng_FactoryProformaInvoiceSearchResult_View>("FactoryProformaInvoiceMng_function_SearchFactoryProformaInvoice", factoryUDParameter, proformaInvoiceNoParameter, seasonParameter, sortedByParameter, sortedDirectionParameter);
        }
    
        public virtual ObjectResult<FactoryProformaInvoiceMng_FactoryProformaInvoiceSearchResult_View> FactoryProformaInvoiceMng_function_SearchFactoryProformaInvoice(string factoryUD, string proformaInvoiceNo, string season, string sortedBy, string sortedDirection, MergeOption mergeOption)
        {
            var factoryUDParameter = factoryUD != null ?
                new ObjectParameter("FactoryUD", factoryUD) :
                new ObjectParameter("FactoryUD", typeof(string));
    
            var proformaInvoiceNoParameter = proformaInvoiceNo != null ?
                new ObjectParameter("ProformaInvoiceNo", proformaInvoiceNo) :
                new ObjectParameter("ProformaInvoiceNo", typeof(string));
    
            var seasonParameter = season != null ?
                new ObjectParameter("Season", season) :
                new ObjectParameter("Season", typeof(string));
    
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryProformaInvoiceMng_FactoryProformaInvoiceSearchResult_View>("FactoryProformaInvoiceMng_function_SearchFactoryProformaInvoice", mergeOption, factoryUDParameter, proformaInvoiceNoParameter, seasonParameter, sortedByParameter, sortedDirectionParameter);
        }
    
        public virtual ObjectResult<FactoryProformaInvoiceMng_FactoryOrderSearchResult_View> FactoryProformaInvoiceMng_function_SearchFactoryOrder(Nullable<int> userID, string season, Nullable<int> factoryID, string query)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var seasonParameter = season != null ?
                new ObjectParameter("Season", season) :
                new ObjectParameter("Season", typeof(string));
    
            var factoryIDParameter = factoryID.HasValue ?
                new ObjectParameter("FactoryID", factoryID) :
                new ObjectParameter("FactoryID", typeof(int));
    
            var queryParameter = query != null ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryProformaInvoiceMng_FactoryOrderSearchResult_View>("FactoryProformaInvoiceMng_function_SearchFactoryOrder", userIDParameter, seasonParameter, factoryIDParameter, queryParameter);
        }
    
        public virtual ObjectResult<FactoryProformaInvoiceMng_FactoryOrderSearchResult_View> FactoryProformaInvoiceMng_function_SearchFactoryOrder(Nullable<int> userID, string season, Nullable<int> factoryID, string query, MergeOption mergeOption)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var seasonParameter = season != null ?
                new ObjectParameter("Season", season) :
                new ObjectParameter("Season", typeof(string));
    
            var factoryIDParameter = factoryID.HasValue ?
                new ObjectParameter("FactoryID", factoryID) :
                new ObjectParameter("FactoryID", typeof(int));
    
            var queryParameter = query != null ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactoryProformaInvoiceMng_FactoryOrderSearchResult_View>("FactoryProformaInvoiceMng_function_SearchFactoryOrder", mergeOption, userIDParameter, seasonParameter, factoryIDParameter, queryParameter);
        }
    }
}
