//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.NormOfProduction.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormOfProductionMng_WorkOrder_View
    {
        public int WorkOrderID { get; set; }
        public string WorkOrderUD { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> WorkOrderStatusID { get; set; }
        public string WorkOrderStatusNM { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientUD { get; set; }
        public string ClientNM { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ArticleCode { get; set; }
        public Nullable<int> WorkCenterID { get; set; }
        public string WorkCenterUD { get; set; }
        public string WorkCenterNM { get; set; }
    }
}
