//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.FactoryRawMaterialMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportMng_ProductGroup_View
    {
        public int ConstantEntryID { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public string ProductGroupNM { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
