//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ClientMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMng_Overview_ShippingPerformanceChart_View
    {
        public long PrimaryID { get; set; }
        public Nullable<int> LateInWeek { get; set; }
        public Nullable<int> TotalContainer { get; set; }
    }
}
