//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ClientMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMng_Overview_ClientContactHistory_View
    {
        public int ClientContactHistoryID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> ContactDate { get; set; }
        public Nullable<System.DateTime> ContactTime { get; set; }
        public string ContactType { get; set; }
        public string CommunicationContent { get; set; }
    
        public virtual ClientMng_Overview_Client_View ClientMng_Overview_Client_View { get; set; }
    }
}
