//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ClientMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMng_ClientContact_View
    {
        public int ClientContactID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Salutation { get; set; }
        public string FullName { get; set; }
        public string CallingName { get; set; }
        public string JobTitle { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsEurofarAgent { get; set; }
        public string EurofarstockUserName { get; set; }
        public string EurofarstockPassword { get; set; }
        public long PrimaryID { get; set; }
        public int DisplayIndex { get; set; }
    
        public virtual ClientMng_Client_View ClientMng_Client_View { get; set; }
    }
}
