//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ClientMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMng_Overview_EurofarPriceOverview_View
    {
        public long PrimaryID { get; set; }
        public string ProformaInvoiceNo { get; set; }
        public string InvoiceDate { get; set; }
        public string ArticleCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> Qnt40HC { get; set; }
        public int OrderQnt { get; set; }
        public string OrderTypeNM { get; set; }
        public Nullable<int> ShippedQnt { get; set; }
        public Nullable<int> LoadedQnt { get; set; }
        public string MaterialNM { get; set; }
        public string ProductionStatus { get; set; }
        public string FactoryUD { get; set; }
        public string LDS { get; set; }
        public string QuotationUD { get; set; }
        public string ManufacturerCountryNM { get; set; }
        public string LocationNM { get; set; }
        public string PriceDifferenceCode { get; set; }
        public Nullable<decimal> PurchasingPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> TargetPrice { get; set; }
        public string QuotationStatusNM { get; set; }
        public string StatusUpdatedDate { get; set; }
        public string Remark { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Transportation { get; set; }
        public decimal Commission { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Season { get; set; }
        public int OfferID { get; set; }
        public int SaleOrderID { get; set; }
        public string ThumbnailLocation { get; set; }
        public string FileLocation { get; set; }
        public string ModelUD { get; set; }
        public string ModelNM { get; set; }
        public Nullable<decimal> LCCostAmount { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<decimal> CommissionAmount { get; set; }
        public Nullable<decimal> DamagesCost { get; set; }
        public Nullable<decimal> GrossMarginAfterInUSD { get; set; }
        public Nullable<decimal> TransportCost { get; set; }
    }
}
