//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.PaymentTermMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_PaymentMethod
    {
        public int ConstantEntryID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public string PaymentMethodNM { get; set; }
    }
}
