//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.BOM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMMng_ProductionPrice_View
    {
        public Nullable<int> ProductionItemTypeID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<int> ProductionItemID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public long PrimaryID { get; set; }
    }
}
