//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.OutsourcingStandardCostFeeMng.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OutsourcingStandardCostFeeMngEntities : DbContext
    {
        public OutsourcingStandardCostFeeMngEntities()
            : base("name=OutsourcingStandardCostFeeMngEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OutsourcingStandardCostFee> OutsourcingStandardCostFee { get; set; }
        public virtual DbSet<OutsourcingStandardCostFeeMng_Model_SearchView> OutsourcingStandardCostFeeMng_Model_SearchView { get; set; }
        public virtual DbSet<OutsourcingStandardCostFeeMng_ModelOnWorkCenter_View> OutsourcingStandardCostFeeMng_ModelOnWorkCenter_View { get; set; }
        public virtual DbSet<OutsourcingStandardCostFeeMng_OutsourcingCost_View> OutsourcingStandardCostFeeMng_OutsourcingCost_View { get; set; }
        public virtual DbSet<OutsourcingStandardCostFeeMng_OutsourcingCostType_View> OutsourcingStandardCostFeeMng_OutsourcingCostType_View { get; set; }
        public virtual DbSet<OutsourcingStandardCostFeeMng_OutsourcingStandardCostFeeDetail_View> OutsourcingStandardCostFeeMng_OutsourcingStandardCostFeeDetail_View { get; set; }
        public virtual DbSet<OutsourcingStandardCostFeeMng_OutsourcingStandardCostFee_View> OutsourcingStandardCostFeeMng_OutsourcingStandardCostFee_View { get; set; }
        public virtual DbSet<OutsourcingStandardCostFeeMng_ModelPiece_SearchView> OutsourcingStandardCostFeeMng_ModelPiece_SearchView { get; set; }
    
        public virtual int OutsourcingStandardCostFeeMng_Function_AutoCreateOutsourcingStandardCostFee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OutsourcingStandardCostFeeMng_Function_AutoCreateOutsourcingStandardCostFee");
        }
    
        public virtual ObjectResult<OutsourcingStandardCostFeeMng_Model_SearchView> OutsourcingStandardCostFeeMng_Function_ModelSearchView(string modelUD)
        {
            var modelUDParameter = modelUD != null ?
                new ObjectParameter("ModelUD", modelUD) :
                new ObjectParameter("ModelUD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OutsourcingStandardCostFeeMng_Model_SearchView>("OutsourcingStandardCostFeeMng_Function_ModelSearchView", modelUDParameter);
        }
    
        public virtual ObjectResult<OutsourcingStandardCostFeeMng_Model_SearchView> OutsourcingStandardCostFeeMng_Function_ModelSearchView(string modelUD, MergeOption mergeOption)
        {
            var modelUDParameter = modelUD != null ?
                new ObjectParameter("ModelUD", modelUD) :
                new ObjectParameter("ModelUD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OutsourcingStandardCostFeeMng_Model_SearchView>("OutsourcingStandardCostFeeMng_Function_ModelSearchView", mergeOption, modelUDParameter);
        }
    }
}
