//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.DevRequestMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevRequestMng_DevRequestFile_View
    {
        public int DevRequestFileID { get; set; }
        public Nullable<int> DevRequestID { get; set; }
        public string Description { get; set; }
        public string FileUD { get; set; }
        public string FileLocation { get; set; }
        public string FriendlyName { get; set; }
    
        public virtual DevRequestMng_DevRequest_View DevRequestMng_DevRequest_View { get; set; }
    }
}
