//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.MaterialTestingMng.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MaterialTestingMngEntities : DbContext
    {
        public MaterialTestingMngEntities()
            : base("name=MaterialTestingMngEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MaterialTestReport> MaterialTestReport { get; set; }
        public virtual DbSet<MaterialTestReportFile> MaterialTestReportFile { get; set; }
        public virtual DbSet<MaterialTestingMng_MaterialTestReportFile_View> MaterialTestingMng_MaterialTestReportFile_View { get; set; }
        public virtual DbSet<MaterialTestingMng_MaterialOption_View> MaterialTestingMng_MaterialOption_View { get; set; }
        public virtual DbSet<MaterialTestingMng_MaterialTesting_SearchFilesView> MaterialTestingMng_MaterialTesting_SearchFilesView { get; set; }
        public virtual DbSet<MaterialTestUsingMaterialStandard> MaterialTestUsingMaterialStandard { get; set; }
        public virtual DbSet<MaterialTestingMng_MaterialTestReportFile_OverView> MaterialTestingMng_MaterialTestReportFile_OverView { get; set; }
        public virtual DbSet<SupportMng_MaterialTestStandard_View> SupportMng_MaterialTestStandard_View { get; set; }
        public virtual DbSet<MaterialTestingMng_SearchMaterialTestStandard_SearchView> MaterialTestingMng_SearchMaterialTestStandard_SearchView { get; set; }
        public virtual DbSet<MaterialTestingMng_MaterialTestStandard_OverView> MaterialTestingMng_MaterialTestStandard_OverView { get; set; }
        public virtual DbSet<MaterialTestingMng_MaterialTestStandard_View> MaterialTestingMng_MaterialTestStandard_View { get; set; }
        public virtual DbSet<MaterialTestingMng_SearchMaterialTesting_View> MaterialTestingMng_SearchMaterialTesting_View { get; set; }
        public virtual DbSet<MaterialTestingMng_MaterialTestReport_View> MaterialTestingMng_MaterialTestReport_View { get; set; }
        public virtual DbSet<MaterialTestingMng_MaterialTestReport_OverView> MaterialTestingMng_MaterialTestReport_OverView { get; set; }
    
        public virtual ObjectResult<MaterialTestingMng_MaterialOption_View> MaterialTestingMng_function_MaterialOption(string searchString)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("SearchString", searchString) :
                new ObjectParameter("SearchString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaterialTestingMng_MaterialOption_View>("MaterialTestingMng_function_MaterialOption", searchStringParameter);
        }
    
        public virtual ObjectResult<MaterialTestingMng_MaterialOption_View> MaterialTestingMng_function_MaterialOption(string searchString, MergeOption mergeOption)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("SearchString", searchString) :
                new ObjectParameter("SearchString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaterialTestingMng_MaterialOption_View>("MaterialTestingMng_function_MaterialOption", mergeOption, searchStringParameter);
        }
    
        public virtual ObjectResult<MaterialTestingMng_SearchMaterialTesting_View> MaterialTestingMng_function_SearchMaterialTesting(string materialTestReportUD, Nullable<bool> isEnabled, string materialOptionUD, string materialOptionNM, string clientNM, string friendlyName, string testStandardNM, Nullable<System.DateTime> testDate, string sortedBy, string sortedDirection)
        {
            var materialTestReportUDParameter = materialTestReportUD != null ?
                new ObjectParameter("MaterialTestReportUD", materialTestReportUD) :
                new ObjectParameter("MaterialTestReportUD", typeof(string));
    
            var isEnabledParameter = isEnabled.HasValue ?
                new ObjectParameter("IsEnabled", isEnabled) :
                new ObjectParameter("IsEnabled", typeof(bool));
    
            var materialOptionUDParameter = materialOptionUD != null ?
                new ObjectParameter("MaterialOptionUD", materialOptionUD) :
                new ObjectParameter("MaterialOptionUD", typeof(string));
    
            var materialOptionNMParameter = materialOptionNM != null ?
                new ObjectParameter("MaterialOptionNM", materialOptionNM) :
                new ObjectParameter("MaterialOptionNM", typeof(string));
    
            var clientNMParameter = clientNM != null ?
                new ObjectParameter("ClientNM", clientNM) :
                new ObjectParameter("ClientNM", typeof(string));
    
            var friendlyNameParameter = friendlyName != null ?
                new ObjectParameter("FriendlyName", friendlyName) :
                new ObjectParameter("FriendlyName", typeof(string));
    
            var testStandardNMParameter = testStandardNM != null ?
                new ObjectParameter("TestStandardNM", testStandardNM) :
                new ObjectParameter("TestStandardNM", typeof(string));
    
            var testDateParameter = testDate.HasValue ?
                new ObjectParameter("TestDate", testDate) :
                new ObjectParameter("TestDate", typeof(System.DateTime));
    
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaterialTestingMng_SearchMaterialTesting_View>("MaterialTestingMng_function_SearchMaterialTesting", materialTestReportUDParameter, isEnabledParameter, materialOptionUDParameter, materialOptionNMParameter, clientNMParameter, friendlyNameParameter, testStandardNMParameter, testDateParameter, sortedByParameter, sortedDirectionParameter);
        }
    
        public virtual ObjectResult<MaterialTestingMng_SearchMaterialTesting_View> MaterialTestingMng_function_SearchMaterialTesting(string materialTestReportUD, Nullable<bool> isEnabled, string materialOptionUD, string materialOptionNM, string clientNM, string friendlyName, string testStandardNM, Nullable<System.DateTime> testDate, string sortedBy, string sortedDirection, MergeOption mergeOption)
        {
            var materialTestReportUDParameter = materialTestReportUD != null ?
                new ObjectParameter("MaterialTestReportUD", materialTestReportUD) :
                new ObjectParameter("MaterialTestReportUD", typeof(string));
    
            var isEnabledParameter = isEnabled.HasValue ?
                new ObjectParameter("IsEnabled", isEnabled) :
                new ObjectParameter("IsEnabled", typeof(bool));
    
            var materialOptionUDParameter = materialOptionUD != null ?
                new ObjectParameter("MaterialOptionUD", materialOptionUD) :
                new ObjectParameter("MaterialOptionUD", typeof(string));
    
            var materialOptionNMParameter = materialOptionNM != null ?
                new ObjectParameter("MaterialOptionNM", materialOptionNM) :
                new ObjectParameter("MaterialOptionNM", typeof(string));
    
            var clientNMParameter = clientNM != null ?
                new ObjectParameter("ClientNM", clientNM) :
                new ObjectParameter("ClientNM", typeof(string));
    
            var friendlyNameParameter = friendlyName != null ?
                new ObjectParameter("FriendlyName", friendlyName) :
                new ObjectParameter("FriendlyName", typeof(string));
    
            var testStandardNMParameter = testStandardNM != null ?
                new ObjectParameter("TestStandardNM", testStandardNM) :
                new ObjectParameter("TestStandardNM", typeof(string));
    
            var testDateParameter = testDate.HasValue ?
                new ObjectParameter("TestDate", testDate) :
                new ObjectParameter("TestDate", typeof(System.DateTime));
    
            var sortedByParameter = sortedBy != null ?
                new ObjectParameter("SortedBy", sortedBy) :
                new ObjectParameter("SortedBy", typeof(string));
    
            var sortedDirectionParameter = sortedDirection != null ?
                new ObjectParameter("SortedDirection", sortedDirection) :
                new ObjectParameter("SortedDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaterialTestingMng_SearchMaterialTesting_View>("MaterialTestingMng_function_SearchMaterialTesting", mergeOption, materialTestReportUDParameter, isEnabledParameter, materialOptionUDParameter, materialOptionNMParameter, clientNMParameter, friendlyNameParameter, testStandardNMParameter, testDateParameter, sortedByParameter, sortedDirectionParameter);
        }
    }
}
