//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.FactoryNorm.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryFinishedProductNormFactoryGoodsProcedure
    {
        public int FactoryFinishedProductNormFactoryGoodsProcedureID { get; set; }
        public Nullable<int> FactoryGoodsProcedureID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual FactoryFinishedProductNorm FactoryFinishedProductNorm { get; set; }
    }
}
