//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.WarehouseTransferMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseTransferDetail
    {
        public int WarehouseTransferDetailID { get; set; }
        public Nullable<int> WarehouseTransferID { get; set; }
        public Nullable<int> ProductionItemID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> FromFactoryWarehouseID { get; set; }
        public Nullable<decimal> ReceivedQnt { get; set; }
        public Nullable<int> ToFactoryWarehouseID { get; set; }
        public Nullable<decimal> DeliveriedQnt { get; set; }
        public string Remark { get; set; }
    
        public virtual WarehouseTransfer WarehouseTransfer { get; set; }
    }
}
