//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.SCMAgendaMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCMAgendaMng_SCMAppointment_View
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCMAgendaMng_SCMAppointment_View()
        {
            this.SCMAgendaMng_SCMAppointmentUser_View = new HashSet<SCMAgendaMng_SCMAppointmentUser_View>();
            this.SCMAgendaMng_SCMAppointmentAttachedFile_View = new HashSet<SCMAgendaMng_SCMAppointmentAttachedFile_View>();
            this.SCMAgendaMng_SCMInspection_View = new HashSet<SCMAgendaMng_SCMInspection_View>();
        }
    
        public int SCMAppointmentID { get; set; }
        public string SCMAppointmentUD { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int PersonInChargeID { get; set; }
        public string PersonInChargeNM { get; set; }
        public string Subject { get; set; }
        public Nullable<int> MeetingLocationID { get; set; }
        public Nullable<int> FactoryID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> RemindTime { get; set; }
        public string FlightDetail { get; set; }
        public string Description { get; set; }
        public string MeetingMinute { get; set; }
        public string ClientUD { get; set; }
        public string ClientNM { get; set; }
        public string OwnerNM { get; set; }
        public string MeetingLocationNM { get; set; }
        public string FactoryUD { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatorName { get; set; }
        public Nullable<bool> HasLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCMAgendaMng_SCMAppointmentUser_View> SCMAgendaMng_SCMAppointmentUser_View { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCMAgendaMng_SCMAppointmentAttachedFile_View> SCMAgendaMng_SCMAppointmentAttachedFile_View { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCMAgendaMng_SCMInspection_View> SCMAgendaMng_SCMInspection_View { get; set; }
    }
}
