//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.FactoryInvoiceMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryInvoiceMng_FactoryInvoiceDetailSearchResult_View
    {
        public long PrimaryID { get; set; }
        public Nullable<int> FactoryInvoiceID { get; set; }
        public string ArticleCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> ClientUD { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public string Remark { get; set; }
    }
}
