//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.FactoryPLCMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryPLCMng_Packaging_View
    {
        public int OfferLineID { get; set; }
        public string PackagingMethodNM { get; set; }
        public Nullable<int> CTNS { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public string HSCode { get; set; }
    }
}
