//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.FactorySpecificationMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorySpecificationMng_FactoryOrderDetail_View
    {
        public long PrimaryID { get; set; }
        public Nullable<int> FactoryOrderDetailID { get; set; }
        public string FactoryOrderUD { get; set; }
        public Nullable<int> OrderQnt { get; set; }
        public Nullable<System.DateTime> LDS { get; set; }
        public Nullable<int> FactoryOrderID { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
    }
}
