//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.AccountMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserId { get; set; }
        public string AspNetUsersId { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public string UserUD { get; set; }
        public string FullName { get; set; }
        public string SkypeID { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public string SignatureImage { get; set; }
        public string PersonalPhoto { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> IsActivated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public byte[] ConcurrencyFlag { get; set; }
        public Nullable<System.DateTime> LastPasswordChanged { get; set; }
        public Nullable<bool> IsForcedToChangePassword { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
    }
}
