//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ShowroomReceiptMng
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowroomReceiptMng_ShowroomReceiptDetail_View
    {
        public ShowroomReceiptMng_ShowroomReceiptDetail_View()
        {
            this.ShowroomReceiptMng_ShowroomReceiptAreaDetail_View = new HashSet<ShowroomReceiptMng_ShowroomReceiptAreaDetail_View>();
        }
    
        public int ShowroomReceiptDetailID { get; set; }
        public Nullable<int> ShowroomReceiptID { get; set; }
        public Nullable<int> ShowroomItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Remark { get; set; }
        public string ArticleCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientUD { get; set; }
        public string ClientNM { get; set; }
    
        public virtual ShowroomReceiptMng_ShowroomReceipt_View ShowroomReceiptMng_ShowroomReceipt_View { get; set; }
        public virtual ICollection<ShowroomReceiptMng_ShowroomReceiptAreaDetail_View> ShowroomReceiptMng_ShowroomReceiptAreaDetail_View { get; set; }
    }
}
