//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.ClientPermissionMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPermissionMng_ClientPermissionDetail_View
    {
        public Nullable<int> ClientPermissionID { get; set; }
        public int ClientPermissionDetailID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string EmployeeNM { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string DisplayText { get; set; }
    
        public virtual ClientPermissionMng_ClientPermission_View ClientPermissionMng_ClientPermission_View { get; set; }
    }
}
