//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.QAQCMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInspector
    {
        public int LogInspectorID { get; set; }
        public Nullable<int> InspectorID { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public Nullable<int> Approval { get; set; }
        public Nullable<int> QAQCID { get; set; }
    }
}
