//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.ProductionItemGroup.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionItemGroupNotification
    {
        public int ProductionItemGroupNotificationID { get; set; }
        public Nullable<int> ProductionItemGroupID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Remark { get; set; }
    
        public virtual ProductionItemGroup ProductionItemGroup { get; set; }
    }
}
