//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.CheckListMng.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListMng_CheckListGroup_View
    {
        public int CheckListGroupID { get; set; }
        public string CheckListGroupUD { get; set; }
        public string CheckListGroupNM { get; set; }
        public string Remark { get; set; }
    }
}
